#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use SEKafka\Queue\WorkCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands

$application->add(new WorkCommand());

$application->run();
